### ISSUE TITLE
camera only distillation的定义？

### ISSUE THREAD

**Issue by LutaoChu** [DevLinyan/Awesome-Knowledge-Distillation-for-Autonomous-Driving#1]
Thanks for good work！
请问camera only distillation的定义？是指student为camera-only的蒸馏吗？
Unidistill是跨模态的统一蒸馏框架，包含camera、lidar、fusion间4种蒸馏路径。归为camera-only不太合适吧

**Comment by DevLinyan** [comment]
Hi @LutaoChu , thanks for pointing it out. We will fix it.
